### ISSUE TITLE
Global Dashboard Update

### ISSUE THREAD

**Issue by div-yansh-1** [openfoodfoundation/integrations#3]
### Description:

**Task List:**
- [x] Updating Global Dashboard with data from other instances for 2022 
- [x] Completing the n8n workflow by adding modules for all the remaining instances
- [x] Documentation (incl. link) to workflows used.

**Comment by div-yansh-1** [comment]
Global Dashboard documentation is in API handbook. [Link](https://ofn-user-guide.gitbook.io/ofn-api-handbook/global-metrics-dashboard)
